// config.h - Generated by EX-Installer v0.0.20 for EX-CommandStation v5.4.6-Prod

#define IP_PORT 2560
#define SCROLLMODE 1

#define  MY_L298_F439 F("MY_L298_F439"), \
 new MotorDriver( 3, 12, UNUSED_PIN, 9, A2, 0.73, 1500, UNUSED_PIN), \
 new MotorDriver( 5, 13, UNUSED_PIN, 6, A3, 1.49, 1500, UNUSED_PIN)
#define MOTOR_SHIELD_TYPE MY_L298_F439 
#define LCD_DRIVER 0x27,20,4
#define WIFI_HOSTNAME "i like trains"
//#define WIFI_SSID "ST-WiFi"
//#define WIFI_PASSWORD "P4kr4TpHJ496vp"
//#define ENABLE_WIFI true
//#define WIFI_CHANNEL 6
//#define WIFI_IP_ADDRESS "192.168.1.52"
#define ENABLE_ETHERNET true
#define IP_ADDRESS { 192, 168, 1, 52 }
#define ROUTER_IP_ADDRESS "192.168.1.254"
#define SUBNET_MASK "255.255.255.0"
//#define WIFI_CONNECT_TIMEOUT 30000