// config.h - Generated by EX-Installer v0.0.20 for EX-CommandStation v5.4.6-Prod

#define IP_PORT 2560
#define SCROLLMODE 1
#define MOTOR_SHIELD_TYPE STANDARD_MOTOR_SHIELD
#define LCD_DRIVER 0x27,20,4
#define WIFI_HOSTNAME "trains"
#define WIFI_SSID "ST-WiFi"
#define WIFI_PASSWORD "P4kr4TpHJ496vp"
#define ENABLE_WIFI true
//#define WIFI_CHANNEL 6
#define WIFI_IP_ADDRESS "192.168.1.52"
#define ROUTER_IP_ADDRESS "192.168.1.254"
#define SUBNET_MASK "255.255.255.0"
#define WIFI_CONNECT_TIMEOUT 30000