// myAutomation.h - Generated by EX-Installer v0.0.20 for EX-CommandStation v5.4.6-Prod

AUTOSTART
SET_TRACK(A,MAIN)
SET_TRACK(B,PROG)
CALL(1)
DONE

#include "myAliases.h"
#include "myTrains.h"
#include "myTurnouts.h"
#include "myControlPanel.h"

DONE

SEQUENCE(1)
  PRINT("Startup sequence")
  IF(TRN1_PIN)
    PRINT("Initial state b THROW")
    THROW(TRN1)
  ELSE
    PRINT("Initial state b CLOSE")
    CLOSE(TRN1)
  ENDIF
  RETURN