// myAutomation.h - Generated by EX-Installer v0.0.20 for EX-CommandStation v5.4.6-Prod

AUTOSTART
SET_TRACK(A,MAIN)
SET_TRACK(B,PROG)
CALL(1)
DONE

#include "myAliases.h"
#include "myTrains.h"
#include "myTurnouts.h"
#include "myControlPanel.h"

// Lights
ONBUTTON(52)
  IF(52)
    UNLATCH(52)
    FADE(116, 4095, 5000)
    FADE(117, 4095, 5000)
    FADE(118, 4095, 5000)
    FADE(119, 4095, 5000)
    FADE(120, 4095, 5000)
  ELSE
    LATCH(52)
    FADE(116, 0, 1000)
    FADE(117, 0, 1000)
    FADE(118, 0, 1000)
    FADE(119, 0, 1000)
    FADE(120, 0, 1000)
  ENDIF

DONE

SEQUENCE(1)
  PRINT("Startup sequence")
  IF(TRN1_PIN)
    PRINT("Initial state b THROW")
    THROW(TRN1)
  ELSE
    PRINT("Initial state b CLOSE")
    CLOSE(TRN1)
  ENDIF
  RETURN
