// TURNOUT CONTROLS
ONBUTTON(CTRL_BTN_1)
  PRINT("Button 1")
  IFTHROWN(TRN1)
    CLOSE(TRN1)
  ELSE
    THROW(TRN1)
  ENDIF
DONE

ONBUTTON(CTRL_BTN_2)
  PRINT("Button 2")
  IFTHROWN(TRN2)
    CLOSE(TRN2)
  ELSE
    THROW(TRN2)
  ENDIF
DONE

ONBUTTON(CTRL_BTN_3)
  PRINT("Button 3")
  IFTHROWN(TRN3)
    CLOSE(TRN3)
  ELSE
    THROW(TRN3)
  ENDIF
DONE

ONBUTTON(CTRL_BTN_4)
  PRINT("Button 4")
  IFTHROWN(TRN4)
    CLOSE(TRN4)
  ELSE
    THROW(TRN4)
  ENDIF
DONE

ONBUTTON(CTRL_BTN_5)
  PRINT("Button 5")
  IFTHROWN(TRN5)
    CLOSE(TRN5)
  ELSE
    THROW(TRN5)
  ENDIF
DONE

ONBUTTON(CTRL_BTN_6)
  PRINT("Button 6")
  IFTHROWN(TRN6)
    CLOSE(TRN6)
  ELSE
    THROW(TRN6)
  ENDIF
DONE

ONBUTTON(CTRL_BTN_7)
  PRINT("Button 7")
  IFTHROWN(TRN7)
    CLOSE(TRN7)
  ELSE
    THROW(TRN7)
  ENDIF
DONE

ONBUTTON(CTRL_BTN_8)
  PRINT("Button 8")
  IFTHROWN(TRN8)
    CLOSE(TRN8)
  ELSE
    THROW(TRN8)
  ENDIF
DONE

ONBUTTON(CTRL_BTN_9)
  PRINT("Button 9")
  IFTHROWN(TRN9)
    CLOSE(TRN9)
  ELSE
    THROW(TRN9)
  ENDIF
DONE

ONBUTTON(CTRL_BTN_10)
  PRINT("Button 10")
  IFTHROWN(TRN10)
    CLOSE(TRN10)
  ELSE
    THROW(TRN10)
  ENDIF
DONE

ONBUTTON(CTRL_BTN_11)
  PRINT("Button 11")
  IFTHROWN(TRN11)
    CLOSE(TRN11)
  ELSE
    THROW(TRN11)
  ENDIF
DONE

ONBUTTON(CTRL_BTN_12)
  PRINT("Button 12")
  IFTHROWN(TRN12)
    CLOSE(TRN12)
  ELSE
    THROW(TRN12)
  ENDIF
DONE

ONBUTTON(CTRL_BTN_13)
  PRINT("Button 13")
  IFTHROWN(TRN13)
    CLOSE(TRN13)
  ELSE
    THROW(TRN13)
  ENDIF
DONE

ONBUTTON(CTRL_BTN_14)
  PRINT("Button 14")
  IFTHROWN(TRN14)
    CLOSE(TRN14)
  ELSE
    THROW(TRN14)
  ENDIF
DONE


// LIGHT CONTROLS

// Street Lights
ONBUTTON(CTRL_BTN_15)
  FOLLOW(15)
DONE

ROUTE(15, "Street Lights")
  IF(CTRL_BTN_15V)
    PRINT("Button 15 OFF")
    RESET(CTRL_BTN_15V)
    RESET(CTRL_BTN_15L)
    FADE(116, 0, 1000)
    FADE(117, 0, 1000)
    FADE(118, 0, 1000)
    FADE(119, 0, 1000)
    FADE(120, 0, 1000)
  ELSE
    PRINT("Button 15 ON")
    SET(CTRL_BTN_15V)
    SET(CTRL_BTN_15L)
    FADE(116, 4095, 5000)
    FADE(117, 4095, 5000)
    FADE(118, 4095, 5000)
    FADE(119, 4095, 5000)
    FADE(120, 4095, 5000)
  ENDIF
DONE

// 
ONBUTTON(CTRL_BTN_16)
  FOLLOW(16)
DONE

ROUTE(16, "Button 16")
  IF(CTRL_BTN_16V)
    PRINT("Button 16 OFF")
    RESET(CTRL_BTN_16V)
    RESET(CTRL_BTN_16L)
  ELSE
    PRINT("Button 16 ON")
    SET(CTRL_BTN_16V)
    SET(CTRL_BTN_16L)
  ENDIF
DONE

// Wind Turbine
ONBUTTON(CTRL_BTN_17)
  FOLLOW(17)
DONE

ROUTE(17, "Wind Turbine")
  IF(CTRL_BTN_17V)
    PRINT("Button 17 OFF")
    RESET(CTRL_BTN_17V)
    RESET(CTRL_BTN_17L)
  ELSE
    PRINT("Button 17 ON")
    SET(CTRL_BTN_17V)
    SET(CTRL_BTN_17L)
  ENDIF
DONE

// 
ONBUTTON(CTRL_BTN_18)
  FOLLOW(18)
DONE

ROUTE(18, "BUTTON 18")
  IF(CTRL_BTN_18V)
    PRINT("Button 18 OFF")
    RESET(CTRL_BTN_18V)
    RESET(CTRL_BTN_18L)
  ELSE
    PRINT("Button 18 ON")
    SET(CTRL_BTN_18V)
    SET(CTRL_BTN_18L)
  ENDIF
DONE

// 
ONBUTTON(CTRL_BTN_19)
  FOLLOW(19)
DONE

ROUTE(19, "BUTTON 19")
  IF(CTRL_BTN_19V)
    PRINT("Button 19 OFF")
    RESET(CTRL_BTN_19V)
    RESET(CTRL_BTN_19L)
  ELSE
    PRINT("Button 19 ON")
    SET(CTRL_BTN_19V)
    SET(CTRL_BTN_19L)
  ENDIF
DONE
