// Turnouts
SERVO_TURNOUT(TRN1, TRN1_PWM, 250, 300, Medium, "Servo 1")
SERVO_TURNOUT(TRN2, TRN2_PWM, 250, 287, Medium, "Servo 2")
SERVO_TURNOUT(TRN3, TRN3_PWM, 235, 282, Medium, "Servo 3")
SERVO_TURNOUT(TRN4, TRN4_PWM, 290, 250, Medium, "Servo 4")
SERVO_TURNOUT(TRN5, TRN5_PWM, 300, 335, Medium, "Servo 5")
SERVO_TURNOUT(TRN6, TRN6_PWM, 304, 270, Medium, "Servo 6")
SERVO_TURNOUT(TRN7, TRN7_PWM, 250, 308, Medium, "Servo 7")
SERVO_TURNOUT(TRN8, TRN8_PWM, 350, 250, Medium, "Servo 8")
SERVO_TURNOUT(TRN9, TRN9_PWM, 250, 285, Medium, "Servo 9")
SERVO_TURNOUT(TRN10, TRN10_PWM, 265, 325, Medium, "Servo 10")
SERVO_TURNOUT(TRN11, TRN11_PWM, 286, 255, Medium, "Servo 11")
SERVO_TURNOUT(TRN12, TRN12_PWM, 310, 260, Medium, "Servo 12")
SERVO_TURNOUT(TRN13, TRN13_PWM, 294, 330, Medium, "Servo 13")
SERVO_TURNOUT(TRN14, TRN14_PWM, 335, 270, Medium, "Servo 14")

// TURNOUT 1
ONTHROW(TRN1)
  PRINT("Throw Turnout 1")
  SET(CTRL_BTN_1L)
  IFCLOSED(TRN3)
    THROW(TRN3)
  ENDIF
DONE
ONCLOSE(TRN1)
  PRINT("Close Turnout 1")
  RESET(CTRL_BTN_1L)
  IFTHROWN(TRN3)
    CLOSE(TRN3)
  ENDIF
DONE

// TURNOUT 2
ONTHROW(TRN2)
  PRINT("Throw Turnout 2")
  SET(CTRL_BTN_2L)
DONE
ONCLOSE(TRN2)
  PRINT("Close Turnout 2")
  RESET(CTRL_BTN_2L)
DONE

// TURNOUT 3
ONTHROW(TRN3)
  PRINT("Throw Turnout 3")
  SET(CTRL_BTN_3L)
  IFCLOSED(TRN3)
    THROW(TRN1)
  ENNDIF
DONE
ONCLOSE(TRN3)
  PRINT("Close Turnout 3")
  RESET(CTRL_BTN_3L)
  IFTHROWN(TRN3)
    CLOSE(TRN1)
  ENDIF
DONE

// TURNOUT 4
ONTHROW(TRN4)
  PRINT("Throw Turnout 4")
  SET(CTRL_BTN_4L)
DONE
ONCLOSE(TRN4)
  PRINT("Close Turnout 4")
  RESET(CTRL_BTN_4L)
DONE

// TURNOUT 5
ONTHROW(TRN5)
  PRINT("Throw Turnout 5")
  SET(CTRL_BTN_5L)
  //THROW(TRN6)
DONE
ONCLOSE(TRN5)
  PRINT("Close Turnout 5")
  RESET(CTRL_BTN_5L)
  //CLOSE(TRN6)
DONE

// TURNOUT 6
ONTHROW(TRN6)
  PRINT("Throw Turnout 6")
  SET(CTRL_BTN_6L)
  //THROW(TRN5)
DONE
ONCLOSE(TRN6)
  PRINT("Close Turnout 6")
  RESET(CTRL_BTN_6L)
  //CLOSE(TRN5)
DONE

// TURNOUT 7
ONTHROW(TRN7)
  PRINT("Throw Turnout 7")
  SET(CTRL_BTN_7L)
DONE
ONCLOSE(TRN7)
  PRINT("Close Turnout 7")
  RESET(CTRL_BTN_7L)
DONE

// TURNOUT 8
ONTHROW(TRN8)
  PRINT("Throw Turnout 8")
  SET(CTRL_BTN_8L)
DONE
ONCLOSE(TRN8)
  PRINT("Close Turnout 8")
  RESET(CTRL_BTN_8L)
DONE

// TURNOUT 9
ONTHROW(TRN9)
  PRINT("Throw Turnout 9")
  SET(CTRL_BTN_9L)
  //THROW(TRN10)
DONE
ONCLOSE(TRN9)
  PRINT("Close Turnout 9")
  RESET(CTRL_BTN_9L)
  //CLOSE(TRN10)
DONE

// TURNOUT 10
ONTHROW(TRN10)
  PRINT("Throw Turnout 10")
  SET(CTRL_BTN_10L)
  //THROW(TRN9)
DONE
ONCLOSE(TRN10)
  PRINT("Close Turnout 10")
  RESET(CTRL_BTN_10L)
  //CLOSE(TRN9)
DONE

// TURNOUT 11
ONTHROW(TRN11)
  PRINT("Throw Turnout 11")
  SET(CTRL_BTN_11L)
  //THROW(TRN12)
DONE
ONCLOSE(TRN11)
  PRINT("Close Turnout 11")
  RESET(CTRL_BTN_11L)
  //CLOSE(TRN12)
DONE

// TURNOUT 12
ONTHROW(TRN12)
  PRINT("Throw Turnout 12")
  SET(CTRL_BTN_12L)
  //THROW(TRN11)
DONE
ONCLOSE(TRN12)
  PRINT("Close Turnout 12")
  RESET(CTRL_BTN_12L)
  //CLOSE(TRN11)
DONE

// TURNOUT 13
ONTHROW(TRN13)
  PRINT("Throw Turnout 13")
  SET(CTRL_BTN_13L)
DONE
ONCLOSE(TRN13)
  PRINT("Close Turnout 13")
  RESET(CTRL_BTN_13L)
DONE

// TURNOUT 14
ONTHROW(TRN14)
  PRINT("Throw Turnout 14")
  SET(CTRL_BTN_14L)
DONE
ONCLOSE(TRN14)
  PRINT("Close Turnout 14")
  RESET(CTRL_BTN_14L)
DONE

